# This is the version of the pipeline being run.
version: "0.1a"

workflow:
    cores: 8
    
##################################################################################################################
###################################################### MAIN ######################################################
##################################################################################################################

# These parameters determine global options for the
# entire pipeline. They must be changed every time
# you want to rerun new data to avoid conflicts.
general: 
        output_dir: "results"
        # A unique name for the project.
        # It will be the name of the project directory.
        project: "K562_ENCODE_ENCSR868FGK_2reps"

 
        # Some portions of the pipeline can be made deterministic
        # by setting a seed. 
        seed: 1

        # Provide the path to the folder of your input files. Set the type of 
        # your input files (FASTQ, bam) in the next line.
        input: "/project/Wellcome_Discovery/liangtid/DPhil_tidy_up/resources/data/K562_ENCODE_ENCSR868FGK"

        # Provide the type of input that you are using. If you select bam, check carefully stage1_bam_to_archrproj_analysis
        # "fastq", "bam" or "bam_no_qc" (not supporting count_matrix option anymore)
        # if using a BAM input, choose "bam" if you want to go through the barcode correction step by AVOCATO;
        # otherwise choose "bam_no_qc" if your BAM does not need any quality control before translating to the fragments file. 
        input_type: "fastq" 

        has_replicates: True

        # Provide the build to which you wish to align
        # reads. 
        genome_build: "hg38"

        # Path to downloaded data
        data_download_to: "data"

alignment:
        # One of [bowtie2, bwamem2]
        aligner: "bwamem2"
        bowtie2_xsize: 2000
bamCoverage:
        # bamCoverage parameter
        # Normalizing method; one of [RPKM, CPM, BPM, RPGC, None]
        normalize: RPKM

        # binsize of base pairs in computating coverage (integer >=1 )
        binSize: 1
peak_calling:
        # Choose peak calling method
        #       "macs" will use macs2 to call peaks and.
        #       "lanceotron" will use lanceotron to call peaks.
        peak_caller: lanceotron

        macs_q_cutoff: 0.05

        # Numeric, lanceotron peak calling parameter,
        # Peak score cutoff to report region in output file (Default:0.5)
        lanceotron_callPeaks_cutoff: 0.5

        # String, lanceotron peak calling parameter,
        # Format of the output file. 
        #       'Web' will mimic the output from the web app, 
        #       'Bed' will create a standard three column bed file.
        lanceotron_callPeaks_format: Bed

        # Numeric, lanceotron peak calling parameter, 
        # Threshold for selecting candidate peaks (Default:4)
        lanceotron_callPeaks_threshold: 4
        
        # Numeric, lanceotron peak calling parameter,
        # Window size for rolling mean to select candidate peaks (Default:400)
        lanceotron_callPeaks_window: 400
        
        # Boolean, lanceotron peak calling parameter,
        # Skip writing the header (Default:FALSE)
        lanceotron_callPeaks_skipheader: FALSE